version: '3.4'


services:

  shortener:
    env_file:
      - ./src/shortener/.env
    build: ./src
    command: >
      python -m
        uvicorn
        shortener.main:app
        --reload
        --workers 1
        --host 0.0.0.0
        --port 8000
    volumes:
      - ./src:/home/url_shortener/src
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
