version: '3.4'


services:

  shortener:
    env_file:
      - ./src/shortener/.env
    build: ./src
    command: >
      python -m
        uvicorn
        shortener.main:app
        --reload
        --workers 1
        --host 0.0.0.0
        --port 8000
    volumes:
      - ./src:/home/url_shortener/src
    ports:
      - 8001:8000
    depends_on:
      # - db
      - mongo

  # db:
  #   image: postgres:15.3
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=shortener

  mongo:
    image: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

    ports:
      - 27017:27017
    # healthcheck:
    #   test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
